IF (OPENMP_FOUND)
  IF (OpenMP_CXX_FLAGS)
    SET_TARGET_PROPERTIES (${TARGET_NAME} PROPERTIES LINK_FLAGS "${OpenMP_CXX_FLAGS}")
  ENDIF ()
ENDIF ()

IF (MPI_CXX_FOUND)
  INCLUDE_DIRECTORIES (${MPI_CXX_INCLUDE_PATH})

  TARGET_LINK_LIBRARIES (${TARGET_NAME} ${MPI_CXX_LIBRARIES})

  IF (MPI_CXX_COMPILE_FLAGS)
    SET_TARGET_PROPERTIES (${TARGET_NAME} PROPERTIES COMPILE_FLAGS "${MPI_CXX_COMPILE_FLAGS}")
  ENDIF ()

  IF (MPI_CXX_LINK_FLAGS)
    SET_TARGET_PROPERTIES (${TARGET_NAME} PROPERTIES LINK_FLAGS "${MPI_CXX_LINK_FLAGS}")
  ENDIF ()
ENDIF ()


